---
title: Ml Dublin.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Machine Learning Dublin
bio: This is a last-Monday-of-the-month meetup group open to professionals and students
  interested in Machine Learning in any of its forms. There are presentations by selected
  guest speakers on different topics, and networking.
description: A meetup group open to professionals and students interested in Machine
  Learning in any of its forms
notice: Machine Learning Dublin is an initiative of the ADAPT&nbsp;Centre for Digital&nbsp;Content&nbsp;Technology
picture: "/assets/images/mld_logo.png"
resume: false
resume-external: true
resume-url: https://adaptcentre.ie
url: https://mldublin.github.io
logo-url: "/"
permalink: "/events/:title/"
analytics-piwik-url: piwik.adaptcentre.ie
analytics-piwik-id: 1
disqus:
  shortname: mydisqus
  categories: []
meetup: Machine-Learning-Dublin
twitter: dublinML
linkedin: groups/8449243
github: MLDublin
email: mldublin@adaptcentre.ie
authors: 
width: normal
projects: false
about: false
blog: false
nav:
- title: Home
  url: "/"
- title: Past Events
  url: "/events/"
read-time: true
show-tags: true
related: true
post-advance-links:
- blog
animation: false
jekyll-archives:
  enabled:
  - year
plugins:
- jekyll-feed
- jekyll-admin
feed:
  path: feed.xml

gems:
- jekyll-seo-tag
- jekyll-gist
- jekyll-archives
- jekyll-admin

jekyll-mentions:
  base_url: https://github.com
